// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/proto/requirement.proto

package requirement

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequirementService_ExtractRequirements_FullMethodName = "/requirement.RequirementService/ExtractRequirements"
	RequirementService_ListRequirements_FullMethodName    = "/requirement.RequirementService/ListRequirements"
	RequirementService_GetRequirement_FullMethodName      = "/requirement.RequirementService/GetRequirement"
	RequirementService_ConfirmRequirement_FullMethodName  = "/requirement.RequirementService/ConfirmRequirement"
	RequirementService_RejectRequirement_FullMethodName   = "/requirement.RequirementService/RejectRequirement"
	RequirementService_SearchRequirements_FullMethodName  = "/requirement.RequirementService/SearchRequirements"
	RequirementService_HealthCheck_FullMethodName         = "/requirement.RequirementService/HealthCheck"
)

// RequirementServiceClient is the client API for RequirementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RequirementService - Python AI Core 暴露的需求管理服务
type RequirementServiceClient interface {
	// 需求提取（LLM）
	ExtractRequirements(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
	// 需求列表
	ListRequirements(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// 获取单个需求
	GetRequirement(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Requirement, error)
	// 确认需求
	ConfirmRequirement(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	// 拒绝需求
	RejectRequirement(ctx context.Context, in *RejectRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	// 搜索需求
	SearchRequirements(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type requirementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRequirementServiceClient(cc grpc.ClientConnInterface) RequirementServiceClient {
	return &requirementServiceClient{cc}
}

func (c *requirementServiceClient) ExtractRequirements(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, RequirementService_ExtractRequirements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) ListRequirements(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, RequirementService_ListRequirements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) GetRequirement(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Requirement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Requirement)
	err := c.cc.Invoke(ctx, RequirementService_GetRequirement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) ConfirmRequirement(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, RequirementService_ConfirmRequirement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) RejectRequirement(ctx context.Context, in *RejectRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, RequirementService_RejectRequirement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) SearchRequirements(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, RequirementService_SearchRequirements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RequirementService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequirementServiceServer is the server API for RequirementService service.
// All implementations must embed UnimplementedRequirementServiceServer
// for forward compatibility.
//
// RequirementService - Python AI Core 暴露的需求管理服务
type RequirementServiceServer interface {
	// 需求提取（LLM）
	ExtractRequirements(context.Context, *ExtractRequest) (*ExtractResponse, error)
	// 需求列表
	ListRequirements(context.Context, *ListRequest) (*ListResponse, error)
	// 获取单个需求
	GetRequirement(context.Context, *GetRequest) (*Requirement, error)
	// 确认需求
	ConfirmRequirement(context.Context, *ConfirmRequest) (*OperationResponse, error)
	// 拒绝需求
	RejectRequirement(context.Context, *RejectRequest) (*OperationResponse, error)
	// 搜索需求
	SearchRequirements(context.Context, *SearchRequest) (*SearchResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedRequirementServiceServer()
}

// UnimplementedRequirementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequirementServiceServer struct{}

func (UnimplementedRequirementServiceServer) ExtractRequirements(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractRequirements not implemented")
}
func (UnimplementedRequirementServiceServer) ListRequirements(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRequirements not implemented")
}
func (UnimplementedRequirementServiceServer) GetRequirement(context.Context, *GetRequest) (*Requirement, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRequirement not implemented")
}
func (UnimplementedRequirementServiceServer) ConfirmRequirement(context.Context, *ConfirmRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmRequirement not implemented")
}
func (UnimplementedRequirementServiceServer) RejectRequirement(context.Context, *RejectRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectRequirement not implemented")
}
func (UnimplementedRequirementServiceServer) SearchRequirements(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchRequirements not implemented")
}
func (UnimplementedRequirementServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRequirementServiceServer) mustEmbedUnimplementedRequirementServiceServer() {}
func (UnimplementedRequirementServiceServer) testEmbeddedByValue()                            {}

// UnsafeRequirementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequirementServiceServer will
// result in compilation errors.
type UnsafeRequirementServiceServer interface {
	mustEmbedUnimplementedRequirementServiceServer()
}

func RegisterRequirementServiceServer(s grpc.ServiceRegistrar, srv RequirementServiceServer) {
	// If the following call panics, it indicates UnimplementedRequirementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequirementService_ServiceDesc, srv)
}

func _RequirementService_ExtractRequirements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).ExtractRequirements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_ExtractRequirements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).ExtractRequirements(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_ListRequirements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).ListRequirements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_ListRequirements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).ListRequirements(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_GetRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).GetRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_GetRequirement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).GetRequirement(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_ConfirmRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).ConfirmRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_ConfirmRequirement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).ConfirmRequirement(ctx, req.(*ConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_RejectRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).RejectRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_RejectRequirement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).RejectRequirement(ctx, req.(*RejectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_SearchRequirements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).SearchRequirements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_SearchRequirements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).SearchRequirements(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequirementService_ServiceDesc is the grpc.ServiceDesc for RequirementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequirementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "requirement.RequirementService",
	HandlerType: (*RequirementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractRequirements",
			Handler:    _RequirementService_ExtractRequirements_Handler,
		},
		{
			MethodName: "ListRequirements",
			Handler:    _RequirementService_ListRequirements_Handler,
		},
		{
			MethodName: "GetRequirement",
			Handler:    _RequirementService_GetRequirement_Handler,
		},
		{
			MethodName: "ConfirmRequirement",
			Handler:    _RequirementService_ConfirmRequirement_Handler,
		},
		{
			MethodName: "RejectRequirement",
			Handler:    _RequirementService_RejectRequirement_Handler,
		},
		{
			MethodName: "SearchRequirements",
			Handler:    _RequirementService_SearchRequirements_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _RequirementService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/requirement.proto",
}
