// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/requirement.proto

package requirement

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Requirement struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Priority        string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Category        string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	SourceQuote     string                 `protobuf:"bytes,7,opt,name=source_quote,json=sourceQuote,proto3" json:"source_quote,omitempty"`
	ConfirmedBy     string                 `protobuf:"bytes,8,opt,name=confirmed_by,json=confirmedBy,proto3" json:"confirmed_by,omitempty"`
	ConfirmedAt     int64                  `protobuf:"varint,9,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	RejectionReason string                 `protobuf:"bytes,10,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Requirement) Reset() {
	*x = Requirement{}
	mi := &file_api_proto_requirement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirement) ProtoMessage() {}

func (x *Requirement) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirement.ProtoReflect.Descriptor instead.
func (*Requirement) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{0}
}

func (x *Requirement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Requirement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Requirement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Requirement) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Requirement) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Requirement) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Requirement) GetSourceQuote() string {
	if x != nil {
		return x.SourceQuote
	}
	return ""
}

func (x *Requirement) GetConfirmedBy() string {
	if x != nil {
		return x.ConfirmedBy
	}
	return ""
}

func (x *Requirement) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

func (x *Requirement) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *Requirement) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Requirement) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Participants  []string               `protobuf:"bytes,4,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_api_proto_requirement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExtractRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExtractRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ExtractRequest) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

type ExtractResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MeetingId      string                 `protobuf:"bytes,2,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Requirements   []*Requirement         `protobuf:"bytes,3,rep,name=requirements,proto3" json:"requirements,omitempty"`
	QuestionsCount int32                  `protobuf:"varint,4,opt,name=questions_count,json=questionsCount,proto3" json:"questions_count,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_api_proto_requirement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExtractResponse) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *ExtractResponse) GetRequirements() []*Requirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *ExtractResponse) GetQuestionsCount() int32 {
	if x != nil {
		return x.QuestionsCount
	}
	return 0
}

func (x *ExtractResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // PENDING, CONFIRMED, REJECTED
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_proto_requirement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requirements  []*Requirement         `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_proto_requirement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetRequirements() []*Requirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *ListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_requirement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConfirmedBy   string                 `protobuf:"bytes,2,opt,name=confirmed_by,json=confirmedBy,proto3" json:"confirmed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_api_proto_requirement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmRequest) GetConfirmedBy() string {
	if x != nil {
		return x.ConfirmedBy
	}
	return ""
}

type RejectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RejectedBy    string                 `protobuf:"bytes,3,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequest) Reset() {
	*x = RejectRequest{}
	mi := &file_api_proto_requirement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequest) ProtoMessage() {}

func (x *RejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequest.ProtoReflect.Descriptor instead.
func (*RejectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{7}
}

func (x *RejectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RejectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RejectRequest) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Requirement   *Requirement           `protobuf:"bytes,2,opt,name=requirement,proto3" json:"requirement,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_api_proto_requirement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{8}
}

func (x *OperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResponse) GetRequirement() *Requirement {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *OperationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_requirement_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{9}
}

func (x *SearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requirements  []*Requirement         `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_requirement_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{10}
}

func (x *SearchResponse) GetRequirements() []*Requirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_requirement_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Services      map[string]bool        `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // db, redis, llm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_requirement_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_requirement_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_requirement_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetServices() map[string]bool {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_api_proto_requirement_proto protoreflect.FileDescriptor

const file_api_proto_requirement_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/requirement.proto\x12\vrequirement\"\xf7\x02\n" +
	"\vRequirement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12!\n" +
	"\fsource_quote\x18\a \x01(\tR\vsourceQuote\x12!\n" +
	"\fconfirmed_by\x18\b \x01(\tR\vconfirmedBy\x12!\n" +
	"\fconfirmed_at\x18\t \x01(\x03R\vconfirmedAt\x12)\n" +
	"\x10rejection_reason\x18\n" +
	" \x01(\tR\x0frejectionReason\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\"\x80\x01\n" +
	"\x0eExtractRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\"\n" +
	"\fparticipants\x18\x04 \x03(\tR\fparticipants\"\xc7\x01\n" +
	"\x0fExtractResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x02 \x01(\tR\tmeetingId\x12<\n" +
	"\frequirements\x18\x03 \x03(\v2\x18.requirement.RequirementR\frequirements\x12'\n" +
	"\x0fquestions_count\x18\x04 \x01(\x05R\x0equestionsCount\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"V\n" +
	"\vListRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x83\x01\n" +
	"\fListResponse\x12<\n" +
	"\frequirements\x18\x01 \x03(\v2\x18.requirement.RequirementR\frequirements\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x0eConfirmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fconfirmed_by\x18\x02 \x01(\tR\vconfirmedBy\"X\n" +
	"\rRejectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vrejected_by\x18\x03 \x01(\tR\n" +
	"rejectedBy\"\x7f\n" +
	"\x11OperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12:\n" +
	"\vrequirement\x18\x02 \x01(\v2\x18.requirement.RequirementR\vrequirement\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"s\n" +
	"\rSearchRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"d\n" +
	"\x0eSearchResponse\x12<\n" +
	"\frequirements\x18\x01 \x03(\v2\x18.requirement.RequirementR\frequirements\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x0f\n" +
	"\rHealthRequest\"\xc8\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12E\n" +
	"\bservices\x18\x03 \x03(\v2).requirement.HealthResponse.ServicesEntryR\bservices\x1a;\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x012\xaf\x04\n" +
	"\x12RequirementService\x12P\n" +
	"\x13ExtractRequirements\x12\x1b.requirement.ExtractRequest\x1a\x1c.requirement.ExtractResponse\x12G\n" +
	"\x10ListRequirements\x12\x18.requirement.ListRequest\x1a\x19.requirement.ListResponse\x12C\n" +
	"\x0eGetRequirement\x12\x17.requirement.GetRequest\x1a\x18.requirement.Requirement\x12Q\n" +
	"\x12ConfirmRequirement\x12\x1b.requirement.ConfirmRequest\x1a\x1e.requirement.OperationResponse\x12O\n" +
	"\x11RejectRequirement\x12\x1a.requirement.RejectRequest\x1a\x1e.requirement.OperationResponse\x12M\n" +
	"\x12SearchRequirements\x12\x1a.requirement.SearchRequest\x1a\x1b.requirement.SearchResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.requirement.HealthRequest\x1a\x1b.requirement.HealthResponseBBZ@github.com/Wisdoverse/project-cell/gateway/api/proto/requirementb\x06proto3"

var (
	file_api_proto_requirement_proto_rawDescOnce sync.Once
	file_api_proto_requirement_proto_rawDescData []byte
)

func file_api_proto_requirement_proto_rawDescGZIP() []byte {
	file_api_proto_requirement_proto_rawDescOnce.Do(func() {
		file_api_proto_requirement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_requirement_proto_rawDesc), len(file_api_proto_requirement_proto_rawDesc)))
	})
	return file_api_proto_requirement_proto_rawDescData
}

var file_api_proto_requirement_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_requirement_proto_goTypes = []any{
	(*Requirement)(nil),       // 0: requirement.Requirement
	(*ExtractRequest)(nil),    // 1: requirement.ExtractRequest
	(*ExtractResponse)(nil),   // 2: requirement.ExtractResponse
	(*ListRequest)(nil),       // 3: requirement.ListRequest
	(*ListResponse)(nil),      // 4: requirement.ListResponse
	(*GetRequest)(nil),        // 5: requirement.GetRequest
	(*ConfirmRequest)(nil),    // 6: requirement.ConfirmRequest
	(*RejectRequest)(nil),     // 7: requirement.RejectRequest
	(*OperationResponse)(nil), // 8: requirement.OperationResponse
	(*SearchRequest)(nil),     // 9: requirement.SearchRequest
	(*SearchResponse)(nil),    // 10: requirement.SearchResponse
	(*HealthRequest)(nil),     // 11: requirement.HealthRequest
	(*HealthResponse)(nil),    // 12: requirement.HealthResponse
	nil,                       // 13: requirement.HealthResponse.ServicesEntry
}
var file_api_proto_requirement_proto_depIdxs = []int32{
	0,  // 0: requirement.ExtractResponse.requirements:type_name -> requirement.Requirement
	0,  // 1: requirement.ListResponse.requirements:type_name -> requirement.Requirement
	0,  // 2: requirement.OperationResponse.requirement:type_name -> requirement.Requirement
	0,  // 3: requirement.SearchResponse.requirements:type_name -> requirement.Requirement
	13, // 4: requirement.HealthResponse.services:type_name -> requirement.HealthResponse.ServicesEntry
	1,  // 5: requirement.RequirementService.ExtractRequirements:input_type -> requirement.ExtractRequest
	3,  // 6: requirement.RequirementService.ListRequirements:input_type -> requirement.ListRequest
	5,  // 7: requirement.RequirementService.GetRequirement:input_type -> requirement.GetRequest
	6,  // 8: requirement.RequirementService.ConfirmRequirement:input_type -> requirement.ConfirmRequest
	7,  // 9: requirement.RequirementService.RejectRequirement:input_type -> requirement.RejectRequest
	9,  // 10: requirement.RequirementService.SearchRequirements:input_type -> requirement.SearchRequest
	11, // 11: requirement.RequirementService.HealthCheck:input_type -> requirement.HealthRequest
	2,  // 12: requirement.RequirementService.ExtractRequirements:output_type -> requirement.ExtractResponse
	4,  // 13: requirement.RequirementService.ListRequirements:output_type -> requirement.ListResponse
	0,  // 14: requirement.RequirementService.GetRequirement:output_type -> requirement.Requirement
	8,  // 15: requirement.RequirementService.ConfirmRequirement:output_type -> requirement.OperationResponse
	8,  // 16: requirement.RequirementService.RejectRequirement:output_type -> requirement.OperationResponse
	10, // 17: requirement.RequirementService.SearchRequirements:output_type -> requirement.SearchResponse
	12, // 18: requirement.RequirementService.HealthCheck:output_type -> requirement.HealthResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_requirement_proto_init() }
func file_api_proto_requirement_proto_init() {
	if File_api_proto_requirement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_requirement_proto_rawDesc), len(file_api_proto_requirement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_requirement_proto_goTypes,
		DependencyIndexes: file_api_proto_requirement_proto_depIdxs,
		MessageInfos:      file_api_proto_requirement_proto_msgTypes,
	}.Build()
	File_api_proto_requirement_proto = out.File
	file_api_proto_requirement_proto_goTypes = nil
	file_api_proto_requirement_proto_depIdxs = nil
}
