"""Deprecated: use shared.integrations.feishu"""
from shared.integrations.feishu import (
    BotHandler,
    CardHandler,
    EventHandler,
    FeishuAPIError,
    FeishuClient,
    FeishuPlatformAdapter,
    MessageRecorder,
    SessionManager,
    feishu_client,
    feishu_error_handler,
    get_feishu_client,
    get_session_manager,
    handle_feishu_response,
    init_feishu_gateway,
    init_handlers,
    retryable_request,
    router,
)

__all__ = [
    "FeishuClient",
    "feishu_client",
    "get_feishu_client",
    "get_session_manager",
    "router",
    "init_feishu_gateway",
    "EventHandler",
    "BotHandler",
    "CardHandler",
    "MessageRecorder",
    "SessionManager",
    "FeishuPlatformAdapter",
    "FeishuAPIError",
    "feishu_error_handler",
    "handle_feishu_response",
    "retryable_request",
    "init_handlers",
]
