"""Disposable real PostgreSQL/API server for synthetic browser acceptance.

This loopback-only fixture creates a fresh schema and deletes only that schema
on shutdown. It is never a deployment or a provider-performance pilot.
"""

import hashlib
import json
import os
import sys
from contextlib import asynccontextmanager
from uuid import uuid4

import uvicorn
from fastapi import Depends, FastAPI
from sqlalchemy import text
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

from shared.config import settings
from shared.control_plane.api import create_control_plane_router
from shared.control_plane.models import AgentRole, BudgetPolicy, CompanyContext, Goal, GoalStatus
from shared.control_plane.store_factory import ControlPlaneStores
from shared.control_plane.tables import control_plane_metadata
from shared.middleware.internal_auth import verify_internal_key

COMPANY_ID = "cmp_roadmap_browser"
DATABASE_URL = os.environ.get("TEST_DATABASE_URL", "")
if not DATABASE_URL.startswith("postgresql+asyncpg://"):
    raise RuntimeError("Disposable TEST_DATABASE_URL PostgreSQL is required")

settings.app_env = "development"
settings.internal_service_key = "synthetic-browser-internal"
settings.control_plane_company_id = COMPANY_ID
settings.control_plane_local_adapter_enabled = True
settings.control_plane_local_adapter_allowlist = "process:dev-browser"
settings.control_plane_operators_json = json.dumps(
    [
        {
            "actor_id": "browser-operator",
            "token_sha256": hashlib.sha256(b"synthetic-browser-operator").hexdigest(),
            "companies": [COMPANY_ID],
            "scopes": ["*"],
        }
    ]
)
schema = "roadmap_browser_" + uuid4().hex
admin = create_async_engine(DATABASE_URL)
engine = create_async_engine(
    DATABASE_URL, connect_args={"server_settings": {"search_path": schema}}
)
sessions = async_sessionmaker(engine, expire_on_commit=False)


@asynccontextmanager
async def session_provider():
    async with sessions() as session:
        try:
            yield session
            await session.commit()
        except BaseException:
            await session.rollback()
            raise


@asynccontextmanager
async def lifespan(app):
    async with admin.begin() as connection:
        await connection.execute(text(f'CREATE SCHEMA "{schema}"'))
    try:
        async with engine.begin() as connection:
            await connection.run_sync(control_plane_metadata.create_all)
        async with session_provider() as session:
            stores = ControlPlaneStores(session)
            await stores.companies.create_company(
                CompanyContext(company_id=COMPANY_ID, name="Synthetic Browser Acceptance Company")
            )
            await stores.goals.create_goal(
                Goal(
                    goal_id="g_browser",
                    company_id=COMPANY_ID,
                    title="Synthetic browser acceptance goal",
                    status=GoalStatus.ACTIVE,
                )
            )
            await stores.budgets.create_budget_policy(
                BudgetPolicy(company_id=COMPANY_ID, scope="company", period="total", limit_usd=10)
            )
            output = {
                "schema_version": "1.0",
                "status": "succeeded",
                "summary": "Synthetic operating report generated by real subprocess",
                "cost_usd": 0.02,
                "output": {"report": "synthetic acceptance output"},
                "artifact_references": [],
            }
            await stores.agent_registry.create_agent_role(
                AgentRole(
                    company_id=COMPANY_ID,
                    agent_id="dev-browser",
                    display_name="Browser Report Executor",
                    adapter_type="process",
                    permissions=["work.execute", "adapter:process", "tool:wakeup"],
                    adapter_config={
                        "command": [sys.executable, "-c", f"print({json.dumps(output)!r})"],
                        "timeout_sec": 10,
                        "max_cost_usd": 0.1,
                        "contract_version": "1.0",
                    },
                )
            )
        yield
    finally:
        await engine.dispose()
        async with admin.begin() as connection:
            await connection.execute(text(f'DROP SCHEMA "{schema}" CASCADE'))
        await admin.dispose()


app = FastAPI(lifespan=lifespan)
app.include_router(
    create_control_plane_router(session_provider=session_provider),
    dependencies=[Depends(verify_internal_key)],
)


@app.get("/health")
async def health():
    return {"status": "ok", "scope": "synthetic_browser_acceptance"}


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8101)
