"""Unit tests for the resumable synthetic first-success operator CLI."""

from __future__ import annotations

import json
import stat
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

from scripts import first_success


class FakeControlPlaneApi:
    def __init__(self) -> None:
        self.company: dict[str, Any] | None = None
        self.goal: dict[str, Any] | None = None
        self.agent: dict[str, Any] | None = None
        self.work_item: dict[str, Any] | None = None
        self.run: dict[str, Any] | None = None
        self.artifact: dict[str, Any] | None = None
        self.budget_policy: dict[str, Any] | None = None
        self.budget_usage: dict[str, Any] | None = None
        self.post_counts: dict[str, int] = {}
        self.events: list[str] = []

    def get(self, path: str, *, params: dict[str, str] | None = None) -> dict[str, Any]:
        params = params or {}
        if path.startswith("/companies/"):
            return self._found(self.company, "company")
        if path == "/goals":
            return {"goals": [self.goal] if self.goal else []}
        if path.startswith("/goals/"):
            return self._found(self.goal, "goal")
        if path.startswith("/agents/"):
            return self._found(self.agent, "agent")
        if path == "/work-items":
            return {"work_items": [self.work_item] if self.work_item else []}
        if path.startswith("/work-items/"):
            return self._found(self.work_item, "work item")
        if path == "/runs":
            return {"runs": [self.run] if self.run else []}
        if path.startswith("/runs/"):
            return self._found(self.run, "run")
        if path == "/artifacts":
            return {"artifacts": [self.artifact] if self.artifact else []}
        if path.startswith("/artifacts/"):
            return self._found(self.artifact, "artifact")
        if path == "/budgets/policies":
            return {"budget_policies": [self.budget_policy] if self.budget_policy else []}
        if path.startswith("/budgets/policies/"):
            return self._found(self.budget_policy, "budget policy")
        if path == "/budgets/usage":
            return {"usage": [self.budget_usage] if self.budget_usage else []}
        raise AssertionError(f"unexpected GET path: {path}")

    def post(self, path: str, body: dict[str, Any]) -> dict[str, Any]:
        self.post_counts[path] = self.post_counts.get(path, 0) + 1
        self.events.append(path)
        if path == "/companies":
            self.company = dict(body)
            return self.company
        if path == "/budgets/policies":
            self.budget_policy = {**body, "budget_id": "bud_first_success"}
            return self.budget_policy
        if path == "/goals":
            self.goal = {**body, "goal_id": "goal_1"}
            return self.goal
        if path == "/agents":
            self.agent = {**body, "role_id": "role_1"}
            return self.agent
        if path == "/work-items":
            self.work_item = {**body, "work_item_id": "work_1"}
            return self.work_item
        if path == "/work-items/work_1/run":
            output = {
                "status": "ok",
                "adapter": "process",
                "cost_usd": 0,
                "summary": "Synthetic operating report generated by the local fixture executor.",
                "response": {
                    "synthetic": True,
                    "report_type": "operating_report",
                    "period": "2026-Q3 sample",
                    "metric_classification": "synthetic_sample",
                    "metrics": {
                        "recognized_revenue_usd": 125000.0,
                        "operating_expense_usd": 83000.0,
                        "net_operating_income_usd": 42000.0,
                        "open_work_items": 7,
                        "at_risk_work_items": 2,
                    },
                },
                "artifact_references": [],
            }
            self.run = {
                "run_id": "run_1",
                "status": "succeeded",
                "started_at": "2026-10-01T00:00:00+00:00",
                "input_event": {
                    "payload": {
                        "input": body["input"],
                    }
                },
                "output_events": [{"payload": {"output": output}}],
            }
            self.artifact = {
                "artifact_id": "art_1",
                "company_id": body["company_id"],
                "work_item_id": "work_1",
                "run_id": "run_1",
                "content_hash": "a" * 64,
            }
            self.budget_usage = {
                "usage_id": "buduse_first_success",
                "company_id": body["company_id"],
                "budget_id": self.agent["budget_policy_id"],
                "run_id": "run_1",
                "cost_usd": 0,
            }
            self.work_item["status"] = "blocked"
            return {
                "run": self.run,
                "output": output,
                "evidence_artifact_id": "art_1",
            }
        if path == "/work-items/work_1/accept":
            self.work_item.setdefault("metadata", {}).update(
                accepted_artifact_id=body["artifact_id"], acceptance_id="acc_1"
            )
            return {
                "acceptance": {
                    "acceptance_id": "acc_1",
                    "artifact_id": body["artifact_id"],
                    "verdict": body["verdict"],
                }
            }
        if path == "/work-items/work_1/close":
            self.work_item["status"] = body["status"]
            return self.work_item
        raise AssertionError(f"unexpected POST path: {path}")

    @staticmethod
    def _found(value: dict[str, Any] | None, name: str) -> dict[str, Any]:
        if value is None:
            raise first_success.ResourceNotFound(f"No {name}.")
        return value


def _options(tmp_path: Path, **overrides: Any) -> first_success.RunOptions:
    values: dict[str, Any] = {
        "base_url": "http://localhost:8000",
        "company_id": "cmp_demo",
        "run_key": "sample-report",
        "checkpoint": tmp_path / "first-success.json",
    }
    values.update(overrides)
    return first_success.RunOptions(**values)


def test_executor_runs_as_process_and_marks_report_synthetic() -> None:
    request = {
        "input": {"fixture": json.loads(first_success.FIXTURE_PATH.read_text(encoding="utf-8"))}
    }

    completed = subprocess.run(
        [
            sys.executable,
            str(Path(first_success.__file__).resolve()),
            "--fixture-executor",
        ],
        input=json.dumps(request),
        capture_output=True,
        check=False,
        text=True,
    )

    response = json.loads(completed.stdout)
    assert completed.returncode == 0
    assert response["schema_version"] == "1.0"
    assert response["status"] == "succeeded"
    assert response["cost_usd"] == 0
    report = response["output"]
    assert report["synthetic"] is True
    assert report["metric_classification"] == "synthetic_sample"
    assert report["metrics"]["net_operating_income_usd"] == 42000
    assert "sample values" in " ".join(report["notes"])


def test_walkthrough_waits_for_explicit_review_and_checkpoint_is_private(tmp_path: Path) -> None:
    api = FakeControlPlaneApi()
    options = _options(tmp_path)

    result = first_success.run_first_success(options, api)
    checkpoint = json.loads(options.checkpoint.read_text(encoding="utf-8"))

    assert result["status"] == "awaiting_explicit_review"
    assert result["accepted"] is False
    assert result["closed"] is False
    assert api.post_counts.get("/work-items/work_1/accept", 0) == 0
    assert api.post_counts.get("/work-items/work_1/close", 0) == 0
    assert stat.S_IMODE(options.checkpoint.stat().st_mode) == 0o600
    assert "CONTROL_PLANE_OPERATOR_TOKEN" not in json.dumps(checkpoint)
    assert checkpoint["run_id"] == "run_1"
    assert checkpoint["artifact_id"] == "art_1"
    assert checkpoint["budget_id"] == "bud_first_success"
    assert checkpoint["budget_usage_id"] == "buduse_first_success"
    assert result["budget_cost_usd"] == 0
    assert api.agent is not None
    assert api.agent["budget_policy_id"] == checkpoint["budget_id"]
    assert api.budget_policy is not None
    assert api.budget_policy["status"] == "active"
    assert api.budget_policy["scope"] == "company"
    assert api.budget_policy["limit_usd"] > 0
    assert api.agent["adapter_config"]["contract_version"] == "1.0"
    assert api.agent["adapter_config"]["max_cost_usd"] == 0
    assert api.events.index("/budgets/policies") < api.events.index("/agents")
    assert api.events.index("/agents") < api.events.index("/work-items/work_1/run")


def test_review_is_explicit_and_resuming_does_not_repeat_completed_effects(
    tmp_path: Path,
) -> None:
    api = FakeControlPlaneApi()
    options = _options(tmp_path)
    first_success.run_first_success(options, api)

    reviewed = first_success.run_first_success(
        _options(tmp_path, review_reason="Reviewed sample report against the fixture."), api
    )
    repeated = first_success.run_first_success(
        _options(tmp_path, review_reason="Reviewed sample report against the fixture."), api
    )

    assert reviewed["status"] == "completed"
    assert reviewed["accepted"] is True
    assert reviewed["closed"] is True
    assert repeated["acceptance_id"] == "acc_1"
    assert api.post_counts["/work-items/work_1/run"] == 1
    assert api.post_counts["/work-items/work_1/accept"] == 1
    assert api.post_counts["/work-items/work_1/close"] == 1


def test_preexisting_active_company_budget_is_reused_without_mutation(tmp_path: Path) -> None:
    api = FakeControlPlaneApi()
    api.budget_policy = {
        "budget_id": "bud_existing",
        "company_id": "cmp_demo",
        "scope": "company",
        "scope_id": None,
        "period": "monthly",
        "limit_usd": 100.0,
        "status": "active",
        "metadata": {"owner": "operator"},
    }

    result = first_success.run_first_success(_options(tmp_path), api)

    assert result["budget_id"] == "bud_existing"
    assert api.post_counts.get("/budgets/policies", 0) == 0
    assert api.budget_policy["metadata"] == {"owner": "operator"}
    assert api.agent is not None
    assert api.agent["budget_policy_id"] == "bud_existing"


def test_checkpoint_revalidates_budget_before_reusing_completed_run(tmp_path: Path) -> None:
    api = FakeControlPlaneApi()
    options = _options(tmp_path)
    first_success.run_first_success(options, api)
    assert api.budget_policy is not None
    api.budget_policy["status"] = "paused"

    with pytest.raises(first_success.FirstSuccessError, match="active company policy"):
        first_success.run_first_success(options, api)

    assert api.post_counts.get("/work-items/work_1/run", 0) == 1


def test_checkpoint_cannot_be_reused_for_another_run_or_api(tmp_path: Path) -> None:
    api = FakeControlPlaneApi()
    first_success.run_first_success(_options(tmp_path), api)

    with pytest.raises(first_success.FirstSuccessError, match="Checkpoint"):
        first_success.run_first_success(_options(tmp_path, run_key="different-run"), api)


def test_agent_http_option_reports_pending_without_faking_handoffs() -> None:
    class NoCalls:
        def get(self, *args: Any, **kwargs: Any) -> dict[str, Any]:
            raise AssertionError("pending agent workflow should not make API calls")

        def post(self, *args: Any, **kwargs: Any) -> dict[str, Any]:
            raise AssertionError("pending agent workflow should not make API calls")

    result = first_success.run_first_success(
        first_success.RunOptions(
            base_url="http://localhost:8000",
            company_id="cmp_demo",
            run_key="sample-report",
            checkpoint=Path("unused-checkpoint.json"),
            workflow="agent-http",
        ),
        NoCalls(),
    )

    assert result["status"] == "pending"
    assert [item["role"] for item in result["known_endpoints"]] == [
        "Requirement Manager",
        "Requirement Manager",
        "PJM",
        "Dev",
        "QA",
    ]
    assert "no stable HTTP handoff contract" in result["reason"]
    assert result["completion_claimed"] is False
    assert len(result["fixed_cases"]) == 4
    assert all(not row["configured"] for row in result["runtime_probes"])


def test_agent_http_probes_only_health_gets_and_never_claims_completion(monkeypatch: Any) -> None:
    requests: list[tuple[str, str]] = []

    class Response:
        status = 200

        def __enter__(self) -> Response:
            return self

        def __exit__(self, *args: Any) -> None:
            return None

        def read(self) -> bytes:
            return b'{"status":"ready"}'

    def fake_urlopen(request: Any, timeout: int) -> Response:
        requests.append((request.get_method(), request.full_url))
        return Response()

    monkeypatch.setattr(first_success, "urlopen", fake_urlopen)
    urls = {name: f"https://{name}.example" for name in first_success.RUNTIME_NAMES}
    result = first_success.agent_workflow_pending(
        "https://control.example", runtime_urls=urls, headers={"X-Internal-Key": "secret"}
    )

    assert len(requests) == 12
    assert all(method == "GET" for method, _ in requests)
    assert all(any(path in url for path in ("/health",)) for _, url in requests)
    assert result["status"] == "pending"
    assert result["completion_claimed"] is False
    assert all(
        all(probe["ok"] for probe in runtime["probes"].values())
        for runtime in result["runtime_probes"]
    )
    assert "secret" not in json.dumps(result)


def test_auth_headers_are_read_from_environment_without_echoing_them() -> None:
    headers = first_success.headers_from_environment(
        {
            "INTERNAL_SERVICE_KEY": "internal-secret-value",
            "CONTROL_PLANE_OPERATOR_TOKEN": "operator-secret-value",
        }
    )

    assert headers == {
        "X-Internal-Key": "internal-secret-value",
        "X-Control-Plane-Operator-Token": "operator-secret-value",
    }
    assert "internal-secret-value" not in json.dumps(
        first_success.agent_workflow_pending("https://cell.example")
    )
