# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from agents.requirement_manager.grpc import requirement_pb2 as requirement__pb2


class RequirementServiceStub(object):
    """RequirementService exposes the requirement manager agent boundary.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractRequirements = channel.unary_unary(
                '/requirement.RequirementService/ExtractRequirements',
                request_serializer=requirement__pb2.ExtractRequest.SerializeToString,
                response_deserializer=requirement__pb2.ExtractResponse.FromString,
                )
        self.ListRequirements = channel.unary_unary(
                '/requirement.RequirementService/ListRequirements',
                request_serializer=requirement__pb2.ListRequest.SerializeToString,
                response_deserializer=requirement__pb2.ListResponse.FromString,
                )
        self.GetRequirement = channel.unary_unary(
                '/requirement.RequirementService/GetRequirement',
                request_serializer=requirement__pb2.GetRequest.SerializeToString,
                response_deserializer=requirement__pb2.Requirement.FromString,
                )
        self.ConfirmRequirement = channel.unary_unary(
                '/requirement.RequirementService/ConfirmRequirement',
                request_serializer=requirement__pb2.ConfirmRequest.SerializeToString,
                response_deserializer=requirement__pb2.OperationResponse.FromString,
                )
        self.RejectRequirement = channel.unary_unary(
                '/requirement.RequirementService/RejectRequirement',
                request_serializer=requirement__pb2.RejectRequest.SerializeToString,
                response_deserializer=requirement__pb2.OperationResponse.FromString,
                )
        self.SearchRequirements = channel.unary_unary(
                '/requirement.RequirementService/SearchRequirements',
                request_serializer=requirement__pb2.SearchRequest.SerializeToString,
                response_deserializer=requirement__pb2.SearchResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/requirement.RequirementService/HealthCheck',
                request_serializer=requirement__pb2.HealthRequest.SerializeToString,
                response_deserializer=requirement__pb2.HealthResponse.FromString,
                )


class RequirementServiceServicer(object):
    """RequirementService exposes the requirement manager agent boundary.
    """

    def ExtractRequirements(self, request, context):
        """Extract requirements from source content with LLM assistance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRequirements(self, request, context):
        """List requirements.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRequirement(self, request, context):
        """Get one requirement.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmRequirement(self, request, context):
        """Confirm a requirement.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectRequirement(self, request, context):
        """Reject a requirement.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchRequirements(self, request, context):
        """Search requirements.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Check capability health.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RequirementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractRequirements': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractRequirements,
                    request_deserializer=requirement__pb2.ExtractRequest.FromString,
                    response_serializer=requirement__pb2.ExtractResponse.SerializeToString,
            ),
            'ListRequirements': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRequirements,
                    request_deserializer=requirement__pb2.ListRequest.FromString,
                    response_serializer=requirement__pb2.ListResponse.SerializeToString,
            ),
            'GetRequirement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRequirement,
                    request_deserializer=requirement__pb2.GetRequest.FromString,
                    response_serializer=requirement__pb2.Requirement.SerializeToString,
            ),
            'ConfirmRequirement': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmRequirement,
                    request_deserializer=requirement__pb2.ConfirmRequest.FromString,
                    response_serializer=requirement__pb2.OperationResponse.SerializeToString,
            ),
            'RejectRequirement': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectRequirement,
                    request_deserializer=requirement__pb2.RejectRequest.FromString,
                    response_serializer=requirement__pb2.OperationResponse.SerializeToString,
            ),
            'SearchRequirements': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchRequirements,
                    request_deserializer=requirement__pb2.SearchRequest.FromString,
                    response_serializer=requirement__pb2.SearchResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=requirement__pb2.HealthRequest.FromString,
                    response_serializer=requirement__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'requirement.RequirementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RequirementService(object):
    """RequirementService exposes the requirement manager agent boundary.
    """

    @staticmethod
    def ExtractRequirements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/requirement.RequirementService/ExtractRequirements',
            requirement__pb2.ExtractRequest.SerializeToString,
            requirement__pb2.ExtractResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListRequirements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/requirement.RequirementService/ListRequirements',
            requirement__pb2.ListRequest.SerializeToString,
            requirement__pb2.ListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRequirement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/requirement.RequirementService/GetRequirement',
            requirement__pb2.GetRequest.SerializeToString,
            requirement__pb2.Requirement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfirmRequirement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/requirement.RequirementService/ConfirmRequirement',
            requirement__pb2.ConfirmRequest.SerializeToString,
            requirement__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RejectRequirement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/requirement.RequirementService/RejectRequirement',
            requirement__pb2.RejectRequest.SerializeToString,
            requirement__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchRequirements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/requirement.RequirementService/SearchRequirements',
            requirement__pb2.SearchRequest.SerializeToString,
            requirement__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/requirement.RequirementService/HealthCheck',
            requirement__pb2.HealthRequest.SerializeToString,
            requirement__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
